name: Build

on:
  pull_request:
    branches: [master, main]
  push:
    branches: ["*"]
    tags: ["*"]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  build:
    uses: SpiralP/github-reusable-workflows/.github/workflows/build.yml@dd7556a6905c9e8fa54f9907194f55f887f5db0d # main
