name: Rust
on: [push]

jobs:
  linux_x86:
    name: Build Linux ${{ matrix.config.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, target: x86_64-unknown-linux-gnu }

    steps:
      - uses: actions/checkout@v2

      - name: Install x86_64 deps
        if: matrix.config.arch == 'x86_64'
        run: |
          sudo apt-get -y update \
          && sudo apt-get -y install curl ca-certificates git gcc g++ build-essential pkg-config \
            libssl-dev libasound2-dev

      - name: Install nightly ${{ matrix.config.target }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.config.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          command: build
          args: --target ${{ matrix.config.target }}

      - name: Test
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          command: test
          args: --target ${{ matrix.config.target }} -- --nocapture

      - name: Build Release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          command: build
          args: --target ${{ matrix.config.target }} --release

      - name: Rename files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mv 'target/${{ matrix.config.target }}/release/chatsounds-cli' \
            './chatsounds-cli-linux-${{ matrix.config.arch }}' \
          && file './chatsounds-cli-linux-${{ matrix.config.arch }}'

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            chatsounds-cli-linux-${{ matrix.config.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
